OPENAI_API_KEY = "Your OPENAI API KEY"
OPENAI_MODEL = "Your OPENAI MODEL NAME e.g gpt-4"

NEO4J_URI = "Your neo4j uri"
NEO4J_USERNAME = "Your neo4j username"
NEO4J_PASSWORD = "Your guns-candles-crime"
